CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'oaciz'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON wordpress.* TO 'oaciz'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123';
